# Generated by Django 2.2.5 on 2020-01-30 07:59

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import nueoffshore.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(choices=[('Lagos', 'Lagos State'), ('River', 'Rivers State'), ('Abuja', 'FCT'), ('Delta', 'Delta State'), ('Enugu', 'Enugu State')], max_length=20)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('requirement', ckeditor_uploader.fields.RichTextUploadingField()),
                ('years_of_experience', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('Full time', 'Full time'), ('Part time', 'Part time'), ('Internship', 'Internship'), ('Contract', 'Contract')], max_length=10)),
                ('last_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('filled', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('cv', models.FileField(upload_to=nueoffshore.models.user_directory_path)),
                ('certification', models.FileField(blank=True, upload_to=nueoffshore.models.user_directory_path)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('degree', models.CharField(blank=True, choices=[('B.Sc', "Bachelor's Degree"), ('M.Sc', "Master's Degree"), ('PhD', 'Doctorate Degree')], max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='nueoffshore.Job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
