# Generated by Django 2.2.5 on 2020-02-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nueoffshore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicants',
            name='age',
            field=models.IntegerField(blank=True, choices=[(19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40)], max_length=10, unique=True),
        ),
    ]
